name: GreenChunk
version: '1.0'
main: xyz.hynse.greenchunk.GreenChunk
api-version: 1.19
folia-supported: true
commands:
  slime:
    description: Check slime at current position
    usage: /slime
    permission: greenchunk.check
    default: true
  greenchunkreload:
    description: Reload the GreenChunk config
    usage: /greenchunkreload
    permission: greenchunk.reload
    aliases:
      - slimereload
