name: GreenChunk
version: ${version}
main: xyz.hynse.greenchunk.GreenChunk
api-version: 1.19
folia-supported: true
commands:
  slime:
    usage: /slime
  slimemap:
    usage: /slimemap
  greenchunkreload:
    usage: /greenchunkreload
    aliases:
      - slimereload
permissions:
  greenchunk.map.item:
    description: Allows players to use the slime map item.
    default: true
  greenchunk.item:
    description: Allows players to use check slime chunk with item.
    default: true
  greenchunk.reload:
    description: Reload the GreenChunk config
    default: false
  greenchunk.map:
    description: Open slimechunk map around current position
    default: true
  greenchunk.check:
    description: Check slime at current position
    default: true

